[package]
name = "avgr"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
itertools = "0.14.0"
parking_lot = "0.12.3"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["serde_derive"] }
serde_json = "1.0.134"
